name = "fwildclusterboot"
uuid = "7f0e0606-7ebb-4cbe-bbf5-5ff5d7774a1f"
authors = ["Alexander Fischer <alexander-fischer1801@t-online.de>"]
version = "0.8.0"

[deps]
WildBootTests = "65c2e505-86ba-4c19-93f1-95506c1443d5"

[compat]
WildBootTests = "0.7.5"
julia = "1.6"
